export const CREATE_WALLET = "CREATE_WALLET";
export const WALLET_CREATED = "WALLET_CREATED";

export const CHANGE_TO_RESTORE = "CHANGE_TO_RESTORE";
export const CHANGE_TO_CREATE = "CHANGE_TO_CREATE";

export const SHOW_ALL_TO_VALIDATOR = "SHOW_ALL_TO_VALIDATOR";
export const SHOW_CANDIDATE_TO_VALIDATOR = "SHOW_CANDIDATE_TO_VALIDATOR";

export const SHOW_ALL_TO_EMPLOYEER = "SHOW_ALL_TO_EMPLOYEER";
export const SHOW_CANDIDATE_TO_EMPLOYEER = "SHOW_CANDIDATE_TO_EMPLOYEER";