export const CREATE_WALLET = "CREATE_WALLET";
export const WALLET_CREATED = "WALLET_CREATED";

export const CHANGE_TO_RESTORE = "CHANGE_TO_RESTORE";
export const CHANGE_TO_CREATE = "CHANGE_TO_CREATE";

export const RESET_ERROR_MESSAGE = "RESET_ERROR_MESSAGE";
export const SET_ERROR = "SET_ERROR";

export const RESET_DATA = "RESET_DATA";
export const SET_WALLET = "SET_WALLET";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LINKEDIN_AUTH_REQUEST = "LINKEDIN_AUTH_REQUEST";
export const COMPANY_SIGNUP_REQUEST = "COMPANY_SIGNUP_REQUEST";
export const CANDIDATE_SIGNUP_REQUEST = "CANDIDATE_SIGNUP_REQUEST";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";