export const CREATE_WALLET = "CREATE_WALLET";
export const WALLET_CREATED = "WALLET_CREATED";
export const LOGOUT = "LOGOUT";

export const CHANGE_TO_RESTORE = "CHANGE_TO_RESTORE";
export const CHANGE_TO_CREATE = "CHANGE_TO_CREATE";

export const SHOW_ALL_TO_VALIDATOR = "SHOW_ALL_TO_VALIDATOR";
export const SHOW_CANDIDATE_TO_VALIDATOR = "SHOW_CANDIDATE_TO_VALIDATOR";

export const SHOW_ALL_TO_EMPLOYEER = "SHOW_ALL_TO_EMPLOYEER";
export const SHOW_CANDIDATE_TO_EMPLOYEER = "SHOW_CANDIDATE_TO_EMPLOYEER";

export const GET_VALIDATOR_DATA = "GET_VALIDATOR_DATA";
export const SET_VALIDATOR_DATA = "SET_VALIDATOR_DATA";
export const SET_VALIDATOR_LOADING = "SET_VALIDATOR_LOADING";
export const SET_VALIDATOR_ERROR = "SET_VALIDATOR_ERROR";

export const GET_CANDIDATE_DATA = "GET_CANDIDATE_DATA";
export const SET_CANDIDATE_DATA = "SET_CANDIDATE_DATA";
export const SET_CANDIDATE_LOADING = "SET_CANDIDATE_LOADING";
export const SET_CANDIDATE_ERROR = "SET_CANDIDATE_ERROR";

export const GET_EMPLOYEER_DATA = "GET_EMPLOYEER_DATA";
export const SET_EMPLOYEER_DATA = "SET_EMPLOYEER_DATA";
export const SET_EMPLOYEER_LOADING = "SET_EMPLOYEER_LOADING";
export const SET_EMPLOYEER_ERROR = "SET_EMPLOYEER_ERROR";

export const GET_VALIDATOR_CLAIMS = "GET_VALIDATOR_CLAIMS";
export const SET_VALIDATOR_CLAIMS = "SET_VALIDATOR_CLAIMS";
export const SET_VALIDATOR_CLAIMS_LOADING = "SET_VALIDATOR_CLAIMS_LOADING";
export const SET_VALIDATOR_CLAIMS_ERROR = "SET_VALIDATOR_CLAIMS_ERROR";

export const GET_EMPLOYEER_CLAIMS = "GET_EMPLOYEER_CLAIMS";
export const SET_EMPLOYEER_CLAIMS = "SET_EMPLOYEER_CLAIMS";
export const SET_EMPLOYEER_CLAIMS_LOADING = "SET_EMPLOYEER_CLAIMS_LOADING";
export const SET_EMPLOYEER_CLAIMS_ERROR = "SET_EMPLOYEER_CLAIMS_ERROR";

export const GET_CLAIMS = "GET_CLAIMS";
export const SET_CLAIMS_HASH = "SET_CLAIMS_HASH";

export const VALIDATE_CLAIM = "VALIDATE_CLAIM";
export const SET_VALIDATED_CLAIM_HASH = "SET_VALIDATED_CLAIM_HASH";

export const VERIFY_CANDIDATE = "VERIFY_CANDIDATE";
export const SET_EMPLOYEER_CLAIM_HASH = "SET_EMPLOYEER_CLAIM_HASH";